/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/tmp/gen_env/../vehicle_captain_its_asn1_specifications/etsi/cpm_ts103324/asn/cdd/ETSI-ITS-CDD.asn"
 * 	`asn1c -D /tmp/gen_env/vcits/cpm -R -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_AccelerationPolarWithZ_H_
#define	_AccelerationPolarWithZ_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AccelerationMagnitude.h"
#include "CartesianAngle.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AccelerationComponent;

/* AccelerationPolarWithZ */
typedef struct AccelerationPolarWithZ {
	AccelerationMagnitude_t	 accelerationMagnitude;
	CartesianAngle_t	 accelerationDirection;
	struct AccelerationComponent	*zAcceleration;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AccelerationPolarWithZ_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AccelerationPolarWithZ;
extern asn_SEQUENCE_specifics_t asn_SPC_AccelerationPolarWithZ_specs_1;
extern asn_TYPE_member_t asn_MBR_AccelerationPolarWithZ_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _AccelerationPolarWithZ_H_ */
#include <asn_internal.h>
