/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/tmp/gen_env/../vehicle_captain_its_asn1_specifications/etsi/cpm_ts103324/asn/cdd/ETSI-ITS-CDD.asn"
 * 	`asn1c -D /tmp/gen_env/vcits/cpm -R -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_MapPosition_H_
#define	_MapPosition_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Identifier1B.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MapReference;
struct LongitudinalLanePosition;

/* MapPosition */
typedef struct MapPosition {
	struct MapReference	*mapReference;	/* OPTIONAL */
	Identifier1B_t	*laneId;	/* OPTIONAL */
	Identifier1B_t	*connectionId;	/* OPTIONAL */
	struct LongitudinalLanePosition	*longitudinalLanePosition;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MapPosition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MapPosition;
extern asn_SEQUENCE_specifics_t asn_SPC_MapPosition_specs_1;
extern asn_TYPE_member_t asn_MBR_MapPosition_1[4];
extern asn_per_constraints_t asn_PER_type_MapPosition_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _MapPosition_H_ */
#include <asn_internal.h>
