/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/tmp/gen_env/../vehicle_captain_its_asn1_specifications/etsi/cpm_ts103324/asn/cdd/ETSI-ITS-CDD.asn"
 * 	`asn1c -D /tmp/gen_env/vcits/cpm -R -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_SequenceOfCartesianPosition3d_H_
#define	_SequenceOfCartesianPosition3d_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CartesianPosition3d;

/* SequenceOfCartesianPosition3d */
typedef struct SequenceOfCartesianPosition3d {
	A_SEQUENCE_OF(struct CartesianPosition3d) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceOfCartesianPosition3d_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceOfCartesianPosition3d;
extern asn_SET_OF_specifics_t asn_SPC_SequenceOfCartesianPosition3d_specs_1;
extern asn_TYPE_member_t asn_MBR_SequenceOfCartesianPosition3d_1[1];
extern asn_per_constraints_t asn_PER_type_SequenceOfCartesianPosition3d_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceOfCartesianPosition3d_H_ */
#include <asn_internal.h>
