FROM ubuntu:24.04

RUN DEBIAN_FRONTEND="noninteractive" apt-get update && apt-get -y install tzdata

RUN apt-get update \
  && apt-get install -y ssh \
      build-essential \
      gcc \
      g++ \
      gdb \
      clang \
      cmake \
      rsync \
      tar \
      python3 \
  && apt-get clean

# install the demo
WORKDIR /tmp/demo
RUN rm -rf *
COPY . .
WORKDIR /tmp/demo/build
RUN cmake ../release && make