/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PerceptionRegionContainer"
 * 	found in "/tmp/gen_env/../vehicle_captain_its_asn1_specifications/etsi/cpm_ts103324/asn/CPM-PerceptionRegionContainer.asn"
 * 	`asn1c -D /tmp/gen_env/vcits/cpm -R -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_PerceptionRegion_H_
#define	_PerceptionRegion_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DeltaTimeMilliSecondSigned.h"
#include "ConfidenceLevel.h"
#include "Shape.h"
#include <BOOLEAN.h>
#include "CardinalNumber1B.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SequenceOfIdentifier1B;
struct PerceivedObjectIds;

/* PerceptionRegion */
typedef struct PerceptionRegion {
	DeltaTimeMilliSecondSigned_t	 measurementDeltaTime;
	ConfidenceLevel_t	 perceptionRegionConfidence;
	Shape_t	 perceptionRegionShape;
	BOOLEAN_t	 shadowingApplies;
	struct SequenceOfIdentifier1B	*sensorIdList;	/* OPTIONAL */
	CardinalNumber1B_t	*numberOfPerceivedObjects;	/* OPTIONAL */
	struct PerceivedObjectIds	*perceivedObjectIds;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PerceptionRegion_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PerceptionRegion;
extern asn_SEQUENCE_specifics_t asn_SPC_PerceptionRegion_specs_1;
extern asn_TYPE_member_t asn_MBR_PerceptionRegion_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _PerceptionRegion_H_ */
#include <asn_internal.h>
