/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-SensorInformationContainer"
 * 	found in "/tmp/gen_env/../vehicle_captain_its_asn1_specifications/etsi/cpm_ts103324/asn/CPM-SensorInformationContainer.asn"
 * 	`asn1c -D /tmp/gen_env/vcits/cpm -R -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_SensorInformation_H_
#define	_SensorInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Identifier1B.h"
#include "SensorType.h"
#include "ConfidenceLevel.h"
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Shape;

/* SensorInformation */
typedef struct SensorInformation {
	Identifier1B_t	 sensorId;
	SensorType_t	 sensorType;
	struct Shape	*perceptionRegionShape;	/* OPTIONAL */
	ConfidenceLevel_t	*perceptionRegionConfidence;	/* OPTIONAL */
	BOOLEAN_t	 shadowingApplies;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SensorInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SensorInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_SensorInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_SensorInformation_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _SensorInformation_H_ */
#include <asn_internal.h>
